/********************************************************************
* ./include/Dictionary_DmpEvtSim.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./include/Dictionary_DmpEvtSim.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionary_DmpEvtSim();
extern void G__cpp_setup_inheritanceDictionary_DmpEvtSim();
extern void G__cpp_setup_typetableDictionary_DmpEvtSim();
extern void G__cpp_setup_memvarDictionary_DmpEvtSim();
extern void G__cpp_setup_globalDictionary_DmpEvtSim();
extern void G__cpp_setup_memfuncDictionary_DmpEvtSim();
extern void G__cpp_setup_funcDictionary_DmpEvtSim();
extern void G__set_cpp_environmentDictionary_DmpEvtSim();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmpEvtMCBgo.h"
#include "DmpEvtMCPrimaryParticle.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_TClass;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_TBuffer;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_TMemberInspector;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_TObject;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_string;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo;
extern G__linked_taginfo G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle;

/* STUB derived class for protected member access */
