#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpSim, 2014-09-25 00:10:46 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 07/03/2014
 *-----------------------------------------------------
 *      Example of how to run simulation of DAMPE
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpSimAlg as  DmpSim     # Load your lib.

#-------------------------------------------------------------------
# Global setting
DMPSW.Core.Set("EventNumber","10")     # MUST event number for simulation!!!
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
#DMPSW.Core.Set("LogLevel","Debug")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.

#-------------------------------------------------------------------
# RootIOSvc options
#DMPSW.RootIOSvc.Set("Input/FileName","./Ex_pion.mac")   # if NOT set, will invoke visualization mode
#DMPSW.RootIOSvc.Set("Input/FileName","./Ex_proton.mac")      # if NOT set, will invoke visualization mode
#DMPSW.RootIOSvc.Set("Input/FileName","./Ex_electron.mac")    # if NOT set, will invoke visualization mode
#DMPSW.RootIOSvc.Set("Output/FileName","./testxxxmpSimData_test00.root")        # if NOT set, will use the input macro name
DMPSW.RootIOSvc.Set("Output/WriteList","Event/MCTruth/PrimaryParticle;Event/MCTruth/Bgo;Event/MCTruth/Psd;Event/MCTruth/Nud")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
simAlg = DmpSim.DmpSimAlg()
#-------------------------------------------------------------------
simAlg.Set("BT/AuxOffset","993.75 123.75 0")  #Auxiliary detector position x, y, z, AuxOffsetX & Y should be consistent with particle gun position x & y which are set in gps micro file. Default value is 0.
simAlg.Set("BT/MagneticFieldValue","1 0 0") #Magnetic field value, default is 0
#simAlg.Set("BT/MagneticFieldPosZ","0")  #Magnetic field position z, default is 0

simAlg.Set("Physics","QGSP_BERT")  # If NOT set, will use QGSP_BIC. argv = {QGSP_BERT,QGSP_BERT_HP, and so on}
#simAlg.Set("Nud/DeltaTime","200")   # if NOT set, will use 100 as default
#simAlg.Set("Gdml",DMPSW.SysPath+"/share/Geometry/EQM")     # must set the path
#simAlg.Set("Gdml",DMPSW.SysPath+"/share/Geometry/BeamTestOctober2014")     # must set the path
#simAlg.Set("Gdml","../../Geometry/EQM/DAMPE.gdml")     # if NOT set, will use $DMPSWGEOMETRY/DAMPE.gdml
#simAlg.Set("Seed","1411903197")
#simAlg.Set("Gdml","../../Geometry/EQM")     # must set the path

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(simAlg)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()


