#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpSim, 2014-09-25 00:10:46 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 07/03/2014
 *-----------------------------------------------------
 *      Example of how to run simulation of DAMPE
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpSimAlg as  DmpSim     # Load your lib.

#-------------------------------------------------------------------
# Global setting
DMPSW.Core.Set("EventNumber","10")     # MUST event number for simulation!!!
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
#DMPSW.Core.Set("LogLevel","Debug")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.

#-------------------------------------------------------------------
# RootIOSvc options
#DMPSW.RootIOSvc.Set("Output/FileName","./DmpSimData_test00.root")   # if NOT set, will use DmpSim_Seed-sim.root
DMPSW.RootIOSvc.Set("Output/WriteList","Event/MCTruth/PrimaryParticle;Event/MCTruth/Bgo;Event/MCTruth/Psd;Event/MCTruth/Nud")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
simAlg = DmpSim.DmpSimAlg()
#-------------------------------------------------------------------
simAlg.Set("Mode","Vis")  # if NOT set, will use batch mode
#simAlg.Set("Physics","QGSP_BERT")  # If NOT set, will use QGSP_BIC
#simAlg.Set("Gdml","../../Geometry/EQM/DAMPE.gdml")     # if NOT set, will use $DMPSWSYS/share/Geometry/FM/DAMPE.gdml
simAlg.Set("Gdml","../../Geometry/BTOctober2014/Setup.gdml")     # if NOT set, will use $DMPSWSYS/share/Geometry/FM/DAMPE.gdml
#simAlg.Set("Seed","1411903197")
simAlg.Set("BT/Magnetic","4 0 0") # default is "0 0 0"
#simAlg.Set("BT/DAMPE/Translation","100 300 0") # default is "0 0 0"
#simAlg.Set("BT/DAMPE/Rotation","100 0 0") # default is "0 0 0"
#-------------------------------------------------------------------
# Set gps   Warning: never use "gps/direction" and "gps/centre" at here
#simAlg.Set("gps/particle","e-")
#simAlg.Set("gps/ene/type","Mono")
#simAlg.Set("gps/ene/mono","2000. Mev")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(simAlg)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()


