//
// File generated by rootcint at Fri Aug 22 21:17:13 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdIincludedIDictionary_DmpEvtSim
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Dictionary_DmpEvtSim.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void DmpEvtMCBgo_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_DmpEvtMCBgo(void *p = 0);
   static void *newArray_DmpEvtMCBgo(Long_t size, void *p);
   static void delete_DmpEvtMCBgo(void *p);
   static void deleteArray_DmpEvtMCBgo(void *p);
   static void destruct_DmpEvtMCBgo(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::DmpEvtMCBgo*)
   {
      ::DmpEvtMCBgo *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DmpEvtMCBgo >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DmpEvtMCBgo", ::DmpEvtMCBgo::Class_Version(), "./include/DmpEvtMCBgo.h", 12,
                  typeid(::DmpEvtMCBgo), DefineBehavior(ptr, ptr),
                  &::DmpEvtMCBgo::Dictionary, isa_proxy, 4,
                  sizeof(::DmpEvtMCBgo) );
      instance.SetNew(&new_DmpEvtMCBgo);
      instance.SetNewArray(&newArray_DmpEvtMCBgo);
      instance.SetDelete(&delete_DmpEvtMCBgo);
      instance.SetDeleteArray(&deleteArray_DmpEvtMCBgo);
      instance.SetDestructor(&destruct_DmpEvtMCBgo);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::DmpEvtMCBgo*)
   {
      return GenerateInitInstanceLocal((::DmpEvtMCBgo*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DmpEvtMCBgo*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void DmpEvtMCPrimaryParticle_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_DmpEvtMCPrimaryParticle(void *p = 0);
   static void *newArray_DmpEvtMCPrimaryParticle(Long_t size, void *p);
   static void delete_DmpEvtMCPrimaryParticle(void *p);
   static void deleteArray_DmpEvtMCPrimaryParticle(void *p);
   static void destruct_DmpEvtMCPrimaryParticle(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::DmpEvtMCPrimaryParticle*)
   {
      ::DmpEvtMCPrimaryParticle *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DmpEvtMCPrimaryParticle >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DmpEvtMCPrimaryParticle", ::DmpEvtMCPrimaryParticle::Class_Version(), "./include/DmpEvtMCPrimaryParticle.h", 12,
                  typeid(::DmpEvtMCPrimaryParticle), DefineBehavior(ptr, ptr),
                  &::DmpEvtMCPrimaryParticle::Dictionary, isa_proxy, 4,
                  sizeof(::DmpEvtMCPrimaryParticle) );
      instance.SetNew(&new_DmpEvtMCPrimaryParticle);
      instance.SetNewArray(&newArray_DmpEvtMCPrimaryParticle);
      instance.SetDelete(&delete_DmpEvtMCPrimaryParticle);
      instance.SetDeleteArray(&deleteArray_DmpEvtMCPrimaryParticle);
      instance.SetDestructor(&destruct_DmpEvtMCPrimaryParticle);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::DmpEvtMCPrimaryParticle*)
   {
      return GenerateInitInstanceLocal((::DmpEvtMCPrimaryParticle*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DmpEvtMCPrimaryParticle*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *DmpEvtMCBgo::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *DmpEvtMCBgo::Class_Name()
{
   return "DmpEvtMCBgo";
}

//______________________________________________________________________________
const char *DmpEvtMCBgo::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtMCBgo*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DmpEvtMCBgo::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtMCBgo*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DmpEvtMCBgo::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtMCBgo*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DmpEvtMCBgo::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtMCBgo*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *DmpEvtMCPrimaryParticle::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *DmpEvtMCPrimaryParticle::Class_Name()
{
   return "DmpEvtMCPrimaryParticle";
}

//______________________________________________________________________________
const char *DmpEvtMCPrimaryParticle::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtMCPrimaryParticle*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DmpEvtMCPrimaryParticle::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtMCPrimaryParticle*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DmpEvtMCPrimaryParticle::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtMCPrimaryParticle*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DmpEvtMCPrimaryParticle::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtMCPrimaryParticle*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void DmpEvtMCBgo::Streamer(TBuffer &R__b)
{
   // Stream an object of class DmpEvtMCBgo.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(DmpEvtMCBgo::Class(),this);
   } else {
      R__b.WriteClassBuffer(DmpEvtMCBgo::Class(),this);
   }
}

//______________________________________________________________________________
void DmpEvtMCBgo::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DmpEvtMCBgo.
      TClass *R__cl = ::DmpEvtMCBgo::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fGlobalBarID", (void*)&fGlobalBarID);
      R__insp.InspectMember("vector<short>", (void*)&fGlobalBarID, "fGlobalBarID.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEnergy", (void*)&fEnergy);
      R__insp.InspectMember("vector<double>", (void*)&fEnergy, "fEnergy.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosX", (void*)&fPosX);
      R__insp.InspectMember("vector<double>", (void*)&fPosX, "fPosX.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosY", (void*)&fPosY);
      R__insp.InspectMember("vector<double>", (void*)&fPosY, "fPosY.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosZ", (void*)&fPosZ);
      R__insp.InspectMember("vector<double>", (void*)&fPosZ, "fPosZ.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_DmpEvtMCBgo(void *p) {
      return  p ? new(p) ::DmpEvtMCBgo : new ::DmpEvtMCBgo;
   }
   static void *newArray_DmpEvtMCBgo(Long_t nElements, void *p) {
      return p ? new(p) ::DmpEvtMCBgo[nElements] : new ::DmpEvtMCBgo[nElements];
   }
   // Wrapper around operator delete
   static void delete_DmpEvtMCBgo(void *p) {
      delete ((::DmpEvtMCBgo*)p);
   }
   static void deleteArray_DmpEvtMCBgo(void *p) {
      delete [] ((::DmpEvtMCBgo*)p);
   }
   static void destruct_DmpEvtMCBgo(void *p) {
      typedef ::DmpEvtMCBgo current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::DmpEvtMCBgo

//______________________________________________________________________________
void DmpEvtMCPrimaryParticle::Streamer(TBuffer &R__b)
{
   // Stream an object of class DmpEvtMCPrimaryParticle.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(DmpEvtMCPrimaryParticle::Class(),this);
   } else {
      R__b.WriteClassBuffer(DmpEvtMCPrimaryParticle::Class(),this);
   }
}

//______________________________________________________________________________
void DmpEvtMCPrimaryParticle::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DmpEvtMCPrimaryParticle.
      TClass *R__cl = ::DmpEvtMCPrimaryParticle::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEventID", &fEventID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTime", &fTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosX", &fPosX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosY", &fPosY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPosZ", &fPosZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDirectionX", &fDirectionX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDirectionY", &fDirectionY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDirectionZ", &fDirectionZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fKineticE", &fKineticE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPDGCode", &fPDGCode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMass", &fMass);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fCharge", &fCharge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fLeptonNo", &fLeptonNo);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBaryonNo", &fBaryonNo);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_DmpEvtMCPrimaryParticle(void *p) {
      return  p ? new(p) ::DmpEvtMCPrimaryParticle : new ::DmpEvtMCPrimaryParticle;
   }
   static void *newArray_DmpEvtMCPrimaryParticle(Long_t nElements, void *p) {
      return p ? new(p) ::DmpEvtMCPrimaryParticle[nElements] : new ::DmpEvtMCPrimaryParticle[nElements];
   }
   // Wrapper around operator delete
   static void delete_DmpEvtMCPrimaryParticle(void *p) {
      delete ((::DmpEvtMCPrimaryParticle*)p);
   }
   static void deleteArray_DmpEvtMCPrimaryParticle(void *p) {
      delete [] ((::DmpEvtMCPrimaryParticle*)p);
   }
   static void destruct_DmpEvtMCPrimaryParticle(void *p) {
      typedef ::DmpEvtMCPrimaryParticle current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::DmpEvtMCPrimaryParticle

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

namespace ROOT {
   void vectorlEshortgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEshortgR_Dictionary();
   static void *new_vectorlEshortgR(void *p = 0);
   static void *newArray_vectorlEshortgR(Long_t size, void *p);
   static void delete_vectorlEshortgR(void *p);
   static void deleteArray_vectorlEshortgR(void *p);
   static void destruct_vectorlEshortgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<short>*)
   {
      vector<short> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<short>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<short>", -2, "vector.dll", 0,
                  typeid(vector<short>), DefineBehavior(ptr, ptr),
                  0, &vectorlEshortgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<short>) );
      instance.SetNew(&new_vectorlEshortgR);
      instance.SetNewArray(&newArray_vectorlEshortgR);
      instance.SetDelete(&delete_vectorlEshortgR);
      instance.SetDeleteArray(&deleteArray_vectorlEshortgR);
      instance.SetDestructor(&destruct_vectorlEshortgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<short> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<short>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEshortgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<short>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEshortgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<short> : new vector<short>;
   }
   static void *newArray_vectorlEshortgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<short>[nElements] : new vector<short>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEshortgR(void *p) {
      delete ((vector<short>*)p);
   }
   static void deleteArray_vectorlEshortgR(void *p) {
      delete [] ((vector<short>*)p);
   }
   static void destruct_vectorlEshortgR(void *p) {
      typedef vector<short> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<short>

/********************************************************
* ./include/Dictionary_DmpEvtSim.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDictionary_DmpEvtSim();

extern "C" void G__set_cpp_environmentDictionary_DmpEvtSim() {
  G__cpp_reset_tagtableDictionary_DmpEvtSim();
}
#include <new>
extern "C" int G__cpp_dllrevDictionary_DmpEvtSim() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DmpEvtMCBgo */
static int G__Dictionary_DmpEvtSim_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtMCBgo* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtMCBgo[n];
     } else {
       p = new((void*) gvp) DmpEvtMCBgo[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtMCBgo;
     } else {
       p = new((void*) gvp) DmpEvtMCBgo;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCBgo*) G__getstructoffset())->AddG4Hit(*(short*) G__Shortref(&libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3])
, *(double*) G__Doubleref(&libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const DmpEvtMCBgo*) G__getstructoffset())->GetFiredBarNo());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const DmpEvtMCBgo*) G__getstructoffset())->GetLayerID((short) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const DmpEvtMCBgo*) G__getstructoffset())->GetBarID((short) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const DmpEvtMCBgo*) G__getstructoffset())->GetGlobalBarID((short) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const DmpEvtMCBgo*) G__getstructoffset())->GetEnergy((short) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((DmpEvtMCBgo*) G__getstructoffset())->GetPosition((short) G__int(libp->para[0]), *(string*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vector<short>* pobj;
         vector<short> xobj = ((DmpEvtMCBgo*) G__getstructoffset())->GetGlobalBarIDCollection();
         pobj = new vector<short>(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DmpEvtMCBgo::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtMCBgo::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DmpEvtMCBgo::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DmpEvtMCBgo::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCBgo*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtMCBgo::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtMCBgo::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtMCBgo::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_168_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtMCBgo::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Dictionary_DmpEvtSim_168_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   DmpEvtMCBgo* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new DmpEvtMCBgo(*(DmpEvtMCBgo*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DmpEvtMCBgo G__TDmpEvtMCBgo;
static int G__Dictionary_DmpEvtSim_168_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DmpEvtMCBgo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DmpEvtMCBgo*) (soff+(sizeof(DmpEvtMCBgo)*i)))->~G__TDmpEvtMCBgo();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DmpEvtMCBgo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DmpEvtMCBgo*) (soff))->~G__TDmpEvtMCBgo();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Dictionary_DmpEvtSim_168_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtMCBgo* dest = (DmpEvtMCBgo*) G__getstructoffset();
   *dest = *(DmpEvtMCBgo*) libp->para[0].ref;
   const DmpEvtMCBgo& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* DmpEvtMCPrimaryParticle */
static int G__Dictionary_DmpEvtSim_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtMCPrimaryParticle* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtMCPrimaryParticle[n];
     } else {
       p = new((void*) gvp) DmpEvtMCPrimaryParticle[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtMCPrimaryParticle;
     } else {
       p = new((void*) gvp) DmpEvtMCPrimaryParticle;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCPrimaryParticle*) G__getstructoffset())->SetEventID(*(long*) G__Longref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCPrimaryParticle*) G__getstructoffset())->SetTime(*(double*) G__Doubleref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCPrimaryParticle*) G__getstructoffset())->SetPosition(*(double*) G__Doubleref(&libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCPrimaryParticle*) G__getstructoffset())->SetDirection(*(double*) G__Doubleref(&libp->para[0]), *(double*) G__Doubleref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCPrimaryParticle*) G__getstructoffset())->SetKineticEnergy(*(double*) G__Doubleref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCPrimaryParticle*) G__getstructoffset())->SetPDGCode(*(int*) G__Intref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCPrimaryParticle*) G__getstructoffset())->SetMass(*(double*) G__Doubleref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCPrimaryParticle*) G__getstructoffset())->SetCharge(*(double*) G__Doubleref(&libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCPrimaryParticle*) G__getstructoffset())->SetComponent(*(int*) G__Intref(&libp->para[0]), *(int*) G__Intref(&libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const long& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->EventID();
         result7->ref = (long) (&obj);
         G__letint(result7, 'l', (long)obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const double& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->Time();
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const double& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->PositionX();
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const double& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->PositionY();
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const double& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->PositionZ();
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const double& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->DirectionX();
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const double& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->DirectionY();
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const double& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->DirectionZ();
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const double& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->KineticEnergy();
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const int& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->PDGcode();
         result7->ref = (long) (&obj);
         G__letint(result7, 'i', (long)obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const double& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->Mass();
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const double& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->Charge();
         result7->ref = (long) (&obj);
         result7->obj.d = (double) (obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const int& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->LeptonNumber();
         result7->ref = (long) (&obj);
         G__letint(result7, 'i', (long)obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const int& obj = ((const DmpEvtMCPrimaryParticle*) G__getstructoffset())->BaryonNumber();
         result7->ref = (long) (&obj);
         G__letint(result7, 'i', (long)obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DmpEvtMCPrimaryParticle::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtMCPrimaryParticle::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DmpEvtMCPrimaryParticle::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DmpEvtMCPrimaryParticle::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtMCPrimaryParticle*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtMCPrimaryParticle::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtMCPrimaryParticle::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtMCPrimaryParticle::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtSim_169_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtMCPrimaryParticle::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Dictionary_DmpEvtSim_169_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   DmpEvtMCPrimaryParticle* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new DmpEvtMCPrimaryParticle(*(DmpEvtMCPrimaryParticle*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DmpEvtMCPrimaryParticle G__TDmpEvtMCPrimaryParticle;
static int G__Dictionary_DmpEvtSim_169_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DmpEvtMCPrimaryParticle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DmpEvtMCPrimaryParticle*) (soff+(sizeof(DmpEvtMCPrimaryParticle)*i)))->~G__TDmpEvtMCPrimaryParticle();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DmpEvtMCPrimaryParticle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DmpEvtMCPrimaryParticle*) (soff))->~G__TDmpEvtMCPrimaryParticle();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Dictionary_DmpEvtSim_169_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtMCPrimaryParticle* dest = (DmpEvtMCPrimaryParticle*) G__getstructoffset();
   *dest = *(DmpEvtMCPrimaryParticle*) libp->para[0].ref;
   const DmpEvtMCPrimaryParticle& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DmpEvtMCBgo */

/* DmpEvtMCPrimaryParticle */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDictionary_DmpEvtSim {
 public:
  G__Sizep2memfuncDictionary_DmpEvtSim(): p(&G__Sizep2memfuncDictionary_DmpEvtSim::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDictionary_DmpEvtSim::*p)();
};

size_t G__get_sizep2memfuncDictionary_DmpEvtSim()
{
  G__Sizep2memfuncDictionary_DmpEvtSim a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDictionary_DmpEvtSim() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo))) {
     DmpEvtMCBgo *G__Lderived;
     G__Lderived=(DmpEvtMCBgo*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo),G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle))) {
     DmpEvtMCPrimaryParticle *G__Lderived;
     G__Lderived=(DmpEvtMCPrimaryParticle*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle),G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDictionary_DmpEvtSim() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DmpEvtMCBgo */
static void G__setup_memvarDmpEvtMCBgo(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo));
   { DmpEvtMCBgo *p; p=(DmpEvtMCBgo*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlEshortcOallocatorlEshortgRsPgR),G__defined_typename("vector<short>"),-1,4,"fGlobalBarID=",0,"unique sensitive detector(minimum detector unit) ID. Bgo bar ID. fGlobalBarID =  layerID*100 + barID");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fEnergy=",0,"unit MeV");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fPosX=",0,"unit mm, position x");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fPosY=",0,"unit mm, position y");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"fPosZ=",0,"unit mm, position z");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* DmpEvtMCPrimaryParticle */
static void G__setup_memvarDmpEvtMCPrimaryParticle(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle));
   { DmpEvtMCPrimaryParticle *p; p=(DmpEvtMCPrimaryParticle*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"fEventID=",0,"event ID");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fTime=",0,"! nanosecond, always = 0");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fPosX=",0,"X position. mm");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fPosY=",0,"Y position. mm");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fPosZ=",0,"Z position. mm");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fDirectionX=",0,"momentum direction X");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fDirectionY=",0,"momentum direction Y");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fDirectionZ=",0,"momentum direction Z");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fKineticE=",0,"kinetic energy. MeV");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fPDGCode=",0,"PDG code");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fMass=",0,"mass. MeV");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"fCharge=",0,"charge");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fLeptonNo=",0,"lepton number");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"fBaryonNo=",0,"baryon number");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDictionary_DmpEvtSim() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDmpEvtMCBgo(void) {
   /* DmpEvtMCBgo */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo));
   G__memfunc_setup("DmpEvtMCBgo",1016,G__Dictionary_DmpEvtSim_168_0_1, 105, G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddG4Hit",681,G__Dictionary_DmpEvtSim_168_0_2, 121, -1, -1, 0, 5, 1, 1, 0, 
"s - - 11 - id d - - 11 - e "
"d - - 11 - x d - - 11 - y "
"d - - 11 - z", "invoke from G4Step or Sensitive Detector", (void*) NULL, 0);
   G__memfunc_setup("GetFiredBarNo",1244,G__Dictionary_DmpEvtSim_168_0_3, 115, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLayerID",938,G__Dictionary_DmpEvtSim_168_0_4, 115, -1, -1, 0, 1, 1, 1, 9, "s - - 0 - entry", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBarID",706,G__Dictionary_DmpEvtSim_168_0_5, 115, -1, -1, 0, 1, 1, 1, 9, "s - - 0 - entry", "in one layer", (void*) NULL, 0);
   G__memfunc_setup("GetGlobalBarID",1299,G__Dictionary_DmpEvtSim_168_0_6, 115, -1, -1, 0, 1, 1, 1, 9, "s - - 0 - entry", "in whole layer", (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__Dictionary_DmpEvtSim_168_0_7, 100, -1, -1, 0, 1, 1, 1, 9, "s - - 0 - entry", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPosition",1141,G__Dictionary_DmpEvtSim_168_0_8, 100, -1, -1, 0, 2, 1, 1, 1, 
"s - - 0 - entry u 'string' - 11 - direction", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetGlobalBarIDCollection",2335,G__Dictionary_DmpEvtSim_168_0_9, 117, G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_vectorlEshortcOallocatorlEshortgRsPgR), G__defined_typename("vector<short>"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Dictionary_DmpEvtSim_168_0_10, 85, G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DmpEvtMCBgo::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Dictionary_DmpEvtSim_168_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtMCBgo::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Dictionary_DmpEvtSim_168_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DmpEvtMCBgo::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Dictionary_DmpEvtSim_168_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DmpEvtMCBgo::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Dictionary_DmpEvtSim_168_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Dictionary_DmpEvtSim_168_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtMCBgo::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Dictionary_DmpEvtSim_168_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtMCBgo::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Dictionary_DmpEvtSim_168_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtMCBgo::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Dictionary_DmpEvtSim_168_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtMCBgo::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("DmpEvtMCBgo", 1016, G__Dictionary_DmpEvtSim_168_0_22, (int) ('i'), G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo), -1, 0, 1, 1, 1, 0, "u 'DmpEvtMCBgo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~DmpEvtMCBgo", 1142, G__Dictionary_DmpEvtSim_168_0_23, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Dictionary_DmpEvtSim_168_0_24, (int) ('u'), G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo), -1, 1, 1, 1, 1, 0, "u 'DmpEvtMCBgo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncDmpEvtMCPrimaryParticle(void) {
   /* DmpEvtMCPrimaryParticle */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle));
   G__memfunc_setup("DmpEvtMCPrimaryParticle",2296,G__Dictionary_DmpEvtSim_169_0_1, 105, G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEventID",955,G__Dictionary_DmpEvtSim_169_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "l - - 11 - i", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTime",699,G__Dictionary_DmpEvtSim_169_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 11 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPosition",1153,G__Dictionary_DmpEvtSim_169_0_4, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 11 - x d - - 11 - y "
"d - - 11 - z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetDirection",1229,G__Dictionary_DmpEvtSim_169_0_5, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 11 - x d - - 11 - y "
"d - - 11 - z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetKineticEnergy",1629,G__Dictionary_DmpEvtSim_169_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 11 - e", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPDGCode",898,G__Dictionary_DmpEvtSim_169_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 11 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMass",704,G__Dictionary_DmpEvtSim_169_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 11 - m", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCharge",886,G__Dictionary_DmpEvtSim_169_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 11 - c", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetComponent",1247,G__Dictionary_DmpEvtSim_169_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 11 - lep i - - 11 - bar", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EventID",655,G__Dictionary_DmpEvtSim_169_0_11, 108, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Time",399,G__Dictionary_DmpEvtSim_169_0_12, 100, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PositionX",941,G__Dictionary_DmpEvtSim_169_0_13, 100, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PositionY",942,G__Dictionary_DmpEvtSim_169_0_14, 100, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PositionZ",943,G__Dictionary_DmpEvtSim_169_0_15, 100, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DirectionX",1017,G__Dictionary_DmpEvtSim_169_0_16, 100, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DirectionY",1018,G__Dictionary_DmpEvtSim_169_0_17, 100, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DirectionZ",1019,G__Dictionary_DmpEvtSim_169_0_18, 100, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("KineticEnergy",1329,G__Dictionary_DmpEvtSim_169_0_19, 100, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PDGcode",630,G__Dictionary_DmpEvtSim_169_0_20, 105, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Mass",404,G__Dictionary_DmpEvtSim_169_0_21, 100, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Charge",586,G__Dictionary_DmpEvtSim_169_0_22, 100, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LeptonNumber",1243,G__Dictionary_DmpEvtSim_169_0_23, 105, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BaryonNumber",1236,G__Dictionary_DmpEvtSim_169_0_24, 105, -1, -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Dictionary_DmpEvtSim_169_0_25, 85, G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DmpEvtMCPrimaryParticle::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Dictionary_DmpEvtSim_169_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtMCPrimaryParticle::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Dictionary_DmpEvtSim_169_0_27, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DmpEvtMCPrimaryParticle::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Dictionary_DmpEvtSim_169_0_28, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DmpEvtMCPrimaryParticle::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Dictionary_DmpEvtSim_169_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Dictionary_DmpEvtSim_169_0_33, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtMCPrimaryParticle::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Dictionary_DmpEvtSim_169_0_34, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtMCPrimaryParticle::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Dictionary_DmpEvtSim_169_0_35, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtMCPrimaryParticle::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Dictionary_DmpEvtSim_169_0_36, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtMCPrimaryParticle::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("DmpEvtMCPrimaryParticle", 2296, G__Dictionary_DmpEvtSim_169_0_37, (int) ('i'), 
G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle), -1, 0, 1, 1, 1, 0, "u 'DmpEvtMCPrimaryParticle' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~DmpEvtMCPrimaryParticle", 2422, G__Dictionary_DmpEvtSim_169_0_38, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Dictionary_DmpEvtSim_169_0_39, (int) ('u'), G__get_linked_tagnum(&G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle), -1, 1, 1, 1, 1, 0, "u 'DmpEvtMCPrimaryParticle' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDictionary_DmpEvtSim() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDictionary_DmpEvtSim() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDictionary_DmpEvtSim() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Dictionary_DmpEvtSimLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo = { "DmpEvtMCBgo" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle = { "DmpEvtMCPrimaryParticle" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDictionary_DmpEvtSim() {
  G__Dictionary_DmpEvtSimLN_TClass.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_TBuffer.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_TMemberInspector.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_TObject.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_string.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo.tagnum = -1 ;
  G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDictionary_DmpEvtSim() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_TClass);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_TObject);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_string);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_DmpEvtMCBgo),sizeof(DmpEvtMCBgo),-1,292096,(char*)NULL,G__setup_memvarDmpEvtMCBgo,G__setup_memfuncDmpEvtMCBgo);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtSimLN_DmpEvtMCPrimaryParticle),sizeof(DmpEvtMCPrimaryParticle),-1,292096,(char*)NULL,G__setup_memvarDmpEvtMCPrimaryParticle,G__setup_memfuncDmpEvtMCPrimaryParticle);
}
extern "C" void G__cpp_setupDictionary_DmpEvtSim(void) {
  G__check_setup_version(30051515,"G__cpp_setupDictionary_DmpEvtSim()");
  G__set_cpp_environmentDictionary_DmpEvtSim();
  G__cpp_setup_tagtableDictionary_DmpEvtSim();

  G__cpp_setup_inheritanceDictionary_DmpEvtSim();

  G__cpp_setup_typetableDictionary_DmpEvtSim();

  G__cpp_setup_memvarDictionary_DmpEvtSim();

  G__cpp_setup_memfuncDictionary_DmpEvtSim();
  G__cpp_setup_globalDictionary_DmpEvtSim();
  G__cpp_setup_funcDictionary_DmpEvtSim();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDictionary_DmpEvtSim();
  return;
}
class G__cpp_setup_initDictionary_DmpEvtSim {
  public:
    G__cpp_setup_initDictionary_DmpEvtSim() { G__add_setup_func("Dictionary_DmpEvtSim",(G__incsetup)(&G__cpp_setupDictionary_DmpEvtSim)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDictionary_DmpEvtSim() { G__remove_setup_func("Dictionary_DmpEvtSim"); }
};
G__cpp_setup_initDictionary_DmpEvtSim G__cpp_setup_initializerDictionary_DmpEvtSim;

